global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'alita-manager'
    static_configs:
      - targets: ['alita-manager:3000']
  
  - job_name: 'alita-web'
    static_configs:
      - targets: ['alita-web:3001']
      
  - job_name: 'kgot-controller'
    static_configs:
      - targets: ['kgot-controller:3003']