# Prometheus Configuration for KGoT-Alita Containerized Services
# Monitors all services with appropriate intervals and targets

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'alita-kgot'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configuration for different service groups
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # === Alita Core Services ===
  
  # Alita Manager Agent
  - job_name: 'alita-manager'
    static_configs:
      - targets: ['alita-manager:3000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    scheme: http

  # Alita Web Agent
  - job_name: 'alita-web'
    static_configs:
      - targets: ['alita-web:3001']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # Alita MCP Creation
  - job_name: 'alita-mcp'
    static_configs:
      - targets: ['alita-mcp:3002']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # === KGoT Core Services ===
  
  # KGoT Controller
  - job_name: 'kgot-controller'
    static_configs:
      - targets: ['kgot-controller:3003']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # KGoT Graph Store
  - job_name: 'kgot-graph-store'
    static_configs:
      - targets: ['kgot-graph-store:3004']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # KGoT Integrated Tools
  - job_name: 'kgot-tools'
    static_configs:
      - targets: ['kgot-tools:3005']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # === Database Services ===
  
  # Neo4j Graph Database
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: redis

  # RDF4J Triplestore
  - job_name: 'rdf4j'
    static_configs:
      - targets: ['rdf4j:8080']
    scrape_interval: 15s
    metrics_path: /rdf4j-server/metrics
    scheme: http

  # === Extension Services ===
  
  # Python Executor
  - job_name: 'python-executor'
    static_configs:
      - targets: ['python-executor:5000']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # Multimodal Processor
  - job_name: 'multimodal-processor'
    static_configs:
      - targets: ['multimodal-processor:3006']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # Validation Service
  - job_name: 'validation-service'
    static_configs:
      - targets: ['validation-service:3007']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # Optimization Service
  - job_name: 'optimization-service'
    static_configs:
      - targets: ['optimization-service:3008']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # === System Monitoring ===
  
  # Node Exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

# Remote write configuration for long-term storage
remote_write:
  - url: "http://prometheus:9090/api/v1/write"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'up|scrape_.*'
        action: drop

# Global limits
global:
  # Maximum number of samples that can be queried at once
  query_max_samples: 50000000
  # Maximum number of samples in a time series that a single query can load
  query_max_concurrent: 20 